### ISSUE TITLE
Compilation fails on Elixir 1.19

### ISSUE THREAD

**Issue by MzudemO** [tallakt/codepagex#38]
Elixir Version: 1.19.0
Erlang Version: 28.1
OS: macOS

Compilation fails, should be fixed by accidentally closed PR #37 

```
❯ mix deps.compile codepagex
==> codepagex
Compiling 5 files (.ex)

... a bunch of errors

== Compilation error in file lib/codepagex/mappings.ex ==
** (exit) an exception was raised:
    ** (UndefinedFunctionError) function Codepagex.MappingFile.load/1 is undefined (module Codepagex.MappingFile is not available)
        Codepagex.MappingFile.load("<app_path>/deps/codepagex/lib/codepagex/../../unicode/ISO8859/8859-13.TXT")
        lib/codepagex/mappings.ex:174: anonymous fn/1 in :elixir_compiler_21.__MODULE__/1
        (elixir 1.19.0) lib/task/supervised.ex:105: Task.Supervised.invoke_mfa/2
        (elixir 1.19.0) lib/task/supervised.ex:40: Task.Supervised.reply/4

could not compile dependency :codepagex, "mix compile" failed. Errors may have been logged above. You can recompile this dependency with "mix deps.compile codepagex --force", update it with "mix deps.update codepagex" or clean it with "mix deps.clean codepagex"
```

**Comment by MzudemO** [comment]
Has been merged, compilation works on Elixir 1.19 now. Thanks!
